### PR TITLE
Make put requests to be type x-www-form-urlencoded just like post calls.

### PR DESCRIPTION
**Pull request by samdotme**
Added a check to make sure that `PUT` requests get treated the same as `POST`.

### CODE REVIEW

**Review by guzumba15 — APPROVED** [review]

**Review by NavathaP — APPROVED** [review]

**Comment by Izzmo** [comment]
@samiam236 did you want to version this as well?

Also I see there is a `dist` directory, but do we need this? Not sure if this was something we included originally but none of our newer repos have it.

**Review by Izzmo — CHANGES_REQUESTED** [review]
Missing a version update.

**Comment by samdotme** [comment]
@Izzmo I thought I needed to wait to add the version tag until after the PR was merged.

Also, this had a pre-existing `dist` folder. But with the way we use currently, there's no need for it. I'll add to `.gitignore`.

**Comment by someyoungideas** [comment]
@samiam236 you still want to update the `package.json` within the pull request.

**Review by someyoungideas — COMMENTED** [review]
@samiam236 you still want to update the `package.json` version within this pull request.

**Comment by samdotme** [comment]
@someyoungideas Ahhh, ok thanks!

I marked this as a bugfix. Is everyone ok with that?

cc @Izzmo

**Review by someyoungideas — APPROVED** [review]

**Review by Izzmo — APPROVED** [review]

**Pull request merged**
